from django.core.exceptions import ValidationError
from .models import Pais, Provincia, Localidad


# def valid_provincia(prov):
